language: python
cache:
  pip: true
  directories:
    - $HOME/.ccache
sudo: required
virtualenv:
  system_site_packages: true
# notifications:
#   email:
#     on_success: always
#     on_failure: always
#   slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
env:
  global:
    - ROSWS=wstool
    - BUILDER=catkin
    - ROS_PARRALEL_JOBS="-j2"
    - CATKIN_PARALLEL_JOBS="-p2"
    - ROS_PARALLEL_TEST_JOBS="-j4"
    - CATKIN_PARALLEL_TEST_JOBS="-p1"
    - ROSDEP_ADDITIONAL_OPTIONS="-n -q -r --ignore-src --as-root pip:no"
    - SUDO_PIP=false
matrix:
  fast_finish: true
  include:
    - dist: precise
      env: ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true CATKIN_TOOLS_BUILD_OPTIONS="-iv --summarize --limit-status-rate 0.002"
    - dist: precise
      env: ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false NOT_TEST_INSTALL=true EXTRA_DEB="ros-hydro-convex-decomposition ros-hydro-ivcon" CATKIN_TOOLS_BUILD_OPTIONS="-iv --summarize --limit-status-rate 0.002"
    - dist: trusty
      env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true USE_TRAVIS=true CATKIN_TOOLS_BUILD_OPTIONS="--summarize --limit-status-rate 0.002"
    - dist: trusty
      env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false USE_TRAVIS=true NOT_TEST_INSTALL=true EXTRA_DEB="ros-indigo-convex-decomposition ros-indigo-ivcon" CATKIN_TOOLS_BUILD_OPTIONS="--summarize --limit-status-rate 0.002"
  allow_failures:
    - dist: precise
      env: ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false NOT_TEST_INSTALL=true EXTRA_DEB="ros-hydro-convex-decomposition ros-hydro-ivcon" CATKIN_TOOLS_BUILD_OPTIONS="-iv --summarize --limit-status-rate 0.002"
    - dist: trusty
      env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false USE_TRAVIS=true NOT_TEST_INSTALL=true EXTRA_DEB="ros-indigo-convex-decomposition ros-indigo-ivcon" CATKIN_TOOLS_BUILD_OPTIONS="--summarize --limit-status-rate 0.002"
install:
  - sudo apt-get install -qq -y python-numpy python-scipy
  - deactivate
  - virtualenv --system-site-packages rosbuild
  - source rosbuild/bin/activate
before_script:
#  - if [ "$ROS_DISTRO" == "indigo" ]; then export BEFORE_SCRIPT="echo \"ros-indigo-pepper-meshes ros-pepper-meshes/accepted-ros-pepper-meshes boolean true\" | sudo debconf-set-selections; sudo apt-get install -y -qq ros-$ROS_DISTRO-pepper-meshes; wget http://packages.ros.org/ros/ubuntu/pool/main/r/ros-indigo-naoqi-libqi/ros-indigo-naoqi-libqi_2.3.0-1trusty-20160109-140942-0800_amd64.deb; sudo dpkg -i --force-depends ros-indigo-naoqi-libqi_2.3.0-1trusty-20160109-140942-0800_amd64.deb; wget http://packages.ros.org/ros/ubuntu/pool/main/r/ros-indigo-naoqi-driver/ros-indigo-naoqi-driver_0.5.7-0trusty-20160203-170424-0800_amd64.deb; sudo dpkg -i --force-depends ros-indigo-naoqi-driver_0.5.7-0trusty-20160203-170424-0800_amd64.deb; wget http://packages.ros.org/ros/ubuntu/pool/main/r/ros-indigo-pepper-bringup/ros-indigo-pepper-bringup_0.1.7-0trusty-20160203-185926-0800_amd64.deb; sudo dpkg -i --force-depends ros-indigo-pepper-bringup_0.1.7-0trusty-20160203-185926-0800_amd64.deb; wget http://packages.ros.org/ros/ubuntu/pool/main/r/ros-indigo-pepper-robot/ros-indigo-pepper-robot_0.1.7-0trusty-20160203-191535-0800_amd64.deb; sudo dpkg -i --force-depends ros-indigo-pepper-robot_0.1.7-0trusty-20160203-191535-0800_amd64.deb; sudo apt-get install -y -f"; fi
  # for deb in ros-indigo-naoqi-libqi_2.3.0-1trusty-20160109-140942-0800_amd64.deb ros-indigo-naoqi-driver_0.5.7-0trusty-20160203-170424-0800_amd64.deb ros-indigo-pepper-bringup_0.1.7-0trusty-20160203-185926-0800_amd64.deb ros-indigo-pepper-robot_0.1.7-0trusty-20160203-191535-0800_amd64.deb; do IFS='_' read -ra package <<< "$deb"; echo -n "wget http://packages.ros.org/ros/ubuntu/pool/main/r/$package/$deb; sudo dpkg -i --force-depends $deb; "; done
script: source .travis/travis.sh
